name: 'Content-Queue Tweet'
description: 'Tweet pending post'
inputs:
  cardContent:
    description: 'Parsed post metadata'
    required: true
  column:
    description: 'Column where issues ready to tweet are stored'
    default: 'To Tweet'
  doneColumn:
    description: "Column where tweeted issues should be stored"
    default: 'Tweeted'
  twitterApiKey:
    description: 'Twitter Consumer API Key'
    required: true
  twitterApiSecret:
    description: 'Twitter Consumer API Secret'
    required: true
  twitterAccessToken:
    description: 'Twitter Access Token'
    required: true
  twitterAccessSecret:
    description: 'Twitter Access Token Secret'
    required: true
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
